config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'page#home'
  resources :hates

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hate.rb
class Hate < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hates_controller.rb
class HatesController < ApplicationController

	def new
		@hate = Hate.new
	end

	def create

		@hate = Hate.new(hate_params)

		if @hate.save
			flash[:notice] = "your hate is successfuly recorded!"
			redirect_to root_path(@hate)
		else
			render 'new'

		end

	end

	def destroy
		@hate = Hate.find(params[:id])
	    @hate.destroy
	    flash[:danger] = "message was successfully deleted"
	    redirect_to root_path
  	end

	private

	def hate_params

		params.require(:hate).permit(:name, :message)

	end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

	def home
		@hate = Hate.all
	end

	


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hates/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Why do you hate mam junifer?</h1>

<%= form_for @hate do |f| %>

<p>

<%= f.label :name %><br/>

<%= f.text_field :name %>

</p>

<p>

<%= f.label :message %><br/>

<%= f.text_area :message %>

</p>

<p>

<%= f.submit %>


</p>
<%= link_to "back to home", root_path %>

<% end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IhateMamJunifer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/_topbar.html.erb
<nav class="navbar navbar-default" >
  <div align="center" class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div align="center">
      
      <a id="webtitle" href="#" >I really really hate Mam junifer</a>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/page/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>I Really Really Hate M'am Junifer!</title>
</head>
<body>
<%= render 'page/topbar' %>
<div  align="center" class="container">
	<% @hate.each do |hate| %>
		<div class="well col-xs-4 col-xs-offset-4">
			<%= hate.name %> says: <br>
			<q><%= hate.message %> </q>
		<div class="col-sm-12">
			<%= link_to "delete message", hate_path(hate), method: :delete, data:{confirm:"Do you want to delete this message?"}, class: "btn btn-danger btn-xs" %>	
		</div>					
		</div>
		
	<% end %>
	<div class="col-sm-12">
		<%= link_to "write a hate message ", new_hate_path, class: "btn btn-primary btn-lg" %>
	</div>
</div>
	
	


</body>
</html>